import type { Prisma, PrismaClient } from "@/generated/prisma";
import { prisma } from "../lib/prisma";
import { decodeAdminCursor, encodeAdminCursor, queryHash, serializeAdminUser, UserAdministrationError, type AdminListQuery, type RoleChangeInput, type StatusChangeInput } from "../user-administration/user-administration.contracts";

const userSelect={id:true,firstName:true,lastName:true,email:true,role:true,status:true,revision:true,createdAt:true,updatedAt:true} as const;
const targetSelect={...userSelect} as const;

export class UserAdministrationService {
 constructor(private readonly db:PrismaClient=prisma){}
 private async actor(tx:Prisma.TransactionClient,actorId:string){const actor=await tx.user.findUnique({where:{id:actorId},select:{id:true,role:true,status:true}});if(!actor||actor.status!=="ACTIVE"||actor.role!=="ADMIN")throw new UserAdministrationError("ADMIN_AUTHORITY_REQUIRED");return actor;}

 async list(actorId:string,query:AdminListQuery){return this.db.$transaction(async tx=>{await this.actor(tx,actorId);const hash=queryHash(query);const cursor=query.cursor?decodeAdminCursor(query.cursor,hash):undefined;const boundary=cursor?{OR:[{createdAt:{lt:new Date(cursor.createdAt)}},{createdAt:new Date(cursor.createdAt),id:{lt:cursor.id}}]}:{};const search=query.search?{OR:[{email:{contains:query.search,mode:"insensitive" as const}},{firstName:{contains:query.search,mode:"insensitive" as const}},{lastName:{contains:query.search,mode:"insensitive" as const}}]}:{};const items=await tx.user.findMany({where:{...search,...(query.role?{role:query.role}:{}),...(query.status?{status:query.status}:{}),...boundary},select:userSelect,orderBy:[{createdAt:"desc"},{id:"desc"}],take:query.limit+1});const page=items.slice(0,query.limit);return{items:page.map(serializeAdminUser),nextCursor:items.length>query.limit?encodeAdminCursor(page[page.length-1],hash):null};});}

 async detail(actorId:string,userId:string){return this.db.$transaction(async tx=>{await this.actor(tx,actorId);const target=await tx.user.findUnique({where:{id:userId},select:userSelect});if(!target)throw new UserAdministrationError("USER_NOT_FOUND");return serializeAdminUser(target);});}

 async changeStatus(actorId:string,userId:string,input:StatusChangeInput){if(actorId===userId)throw new UserAdministrationError("SELF_CHANGE_FORBIDDEN");return this.serialized(async tx=>{await this.actor(tx,actorId);const target=await tx.user.findUnique({where:{id:userId},select:targetSelect});if(!target)throw new UserAdministrationError("USER_NOT_FOUND");this.preconditions(target.revision,input.expectedRevision,target.status,input.expectedStatus,"EXPECTED_STATE_MISMATCH");if(target.status==="ACTIVE"&&target.role==="ADMIN"&&input.status!=="ACTIVE")await this.protectLastAdmin(tx);if(target.status===input.status)return serializeAdminUser(target);const revision=target.revision+1;const updated=await tx.user.update({where:{id:userId},data:{status:input.status,revision},select:userSelect});await tx.administrativeAuditEvent.create({data:{actorUserId:actorId,targetUserId:userId,action:"ACCOUNT_STATUS_CHANGED",beforeValue:target.status,afterValue:input.status,reason:input.reason,targetRevision:revision}});return serializeAdminUser(updated);});}

 async changeRole(actorId:string,userId:string,input:RoleChangeInput){if(actorId===userId)throw new UserAdministrationError("SELF_CHANGE_FORBIDDEN");return this.serialized(async tx=>{await this.actor(tx,actorId);const target=await tx.user.findUnique({where:{id:userId},select:targetSelect});if(!target)throw new UserAdministrationError("USER_NOT_FOUND");this.preconditions(target.revision,input.expectedRevision,target.role,input.expectedRole,"EXPECTED_ROLE_MISMATCH");if(target.status==="ACTIVE"&&target.role==="ADMIN"&&input.role!=="ADMIN")await this.protectLastAdmin(tx);if(target.role===input.role)return serializeAdminUser(target);const revision=target.revision+1;const updated=await tx.user.update({where:{id:userId},data:{role:input.role,revision},select:userSelect});await tx.administrativeAuditEvent.create({data:{actorUserId:actorId,targetUserId:userId,action:"GLOBAL_ROLE_CHANGED",beforeValue:target.role,afterValue:input.role,reason:input.reason,targetRevision:revision}});return serializeAdminUser(updated);});}

 async audit(actorId:string,userId:string,rawCursor?:string,limit=25){return this.db.$transaction(async tx=>{await this.actor(tx,actorId);if(!await tx.user.findUnique({where:{id:userId},select:{id:true}}))throw new UserAdministrationError("USER_NOT_FOUND");if(!Number.isInteger(limit)||limit<1||limit>50)throw new UserAdministrationError("INVALID_FILTER");const cursor=rawCursor?decodeAdminCursor(rawCursor,"audit"):undefined;const items=await tx.administrativeAuditEvent.findMany({where:{targetUserId:userId,...(cursor?{OR:[{createdAt:{lt:new Date(cursor.createdAt)}},{createdAt:new Date(cursor.createdAt),id:{lt:cursor.id}}]}:{})},select:{id:true,targetUserId:true,actorUserId:true,action:true,beforeValue:true,afterValue:true,reason:true,targetRevision:true,createdAt:true},orderBy:[{createdAt:"desc"},{id:"desc"}],take:limit+1});const page=items.slice(0,limit);return{items:page.map(item=>({...item,createdAt:item.createdAt.toISOString()})),nextCursor:items.length>limit?encodeAdminCursor(page[page.length-1],"audit"):null};});}

 private preconditions(currentRevision:number,expectedRevision:number,currentValue:string,expectedValue:string,mismatch:"EXPECTED_STATE_MISMATCH"|"EXPECTED_ROLE_MISMATCH"){if(currentRevision!==expectedRevision)throw new UserAdministrationError("STALE_REVISION",currentRevision);if(currentValue!==expectedValue)throw new UserAdministrationError(mismatch,currentRevision);}
 private async protectLastAdmin(tx:Prisma.TransactionClient){if(await tx.user.count({where:{role:"ADMIN",status:"ACTIVE"}})<=1)throw new UserAdministrationError("LAST_ACTIVE_ADMIN");}
 private async serialized<T>(run:(tx:Prisma.TransactionClient)=>Promise<T>){try{return await this.db.$transaction(run,{isolationLevel:"Serializable"});}catch(error){if(typeof error==="object"&&error!==null&&"code" in error&&(error as {code?:string}).code==="P2034")throw new UserAdministrationError("STALE_REVISION");throw error;}}
}
export const userAdministrationService=new UserAdministrationService();
