import assert from "node:assert/strict";
import { it } from "node:test";
import { createTerritorialMapHandler } from "../../src/app/api/laboratories/[laboratoryId]/territorial-map/route.handlers";
import { AreaAccessError } from "../../src/app/api/server/areas/area.authorization";
import { AuthBoundaryError } from "../../src/app/api/server/middlewares/auth.middleware";
const lab = "10000000-0000-4000-8000-000000000101";
const principal = { id: "user", firstName: "A", lastName: "B", image: "", role: "USER" as const, };
const route = { params: Promise.resolve({ laboratoryId: lab }) };
it("derives the principal, forwards context and returns no-store", async () => { let args: unknown[] = []; const handler = createTerritorialMapHandler({ requireAuth: async () => principal, service: { read: async (...values) => { args = values; return { context: {}, areas: [] } as never; } } }); const response = await handler(new Request("http://localhost"), route); assert.equal(response.status, 200); assert.equal(response.headers.get("cache-control"), "no-store"); assert.deepEqual(args, ["user", lab]); });
it("sanitizes unauthenticated, inaccessible and internal failures", async () => { for (const [error, status, code] of [[new AuthBoundaryError("UNAUTHORIZED"), 401, "UNAUTHENTICATED"], [new AreaAccessError("NOT_FOUND"), 404, "NOT_FOUND"], [new Error("private SQL"), 500, "INTERNAL_ERROR"]] as const) { const handler = createTerritorialMapHandler({ requireAuth: async () => { throw error; }, service: { read: async () => ({} as never) } }); const response = await handler(new Request("http://localhost"), route); assert.equal(response.status, status); assert.equal(response.headers.get("cache-control"), "no-store"); const body = await response.json(); assert.equal(body.error.code, code); assert.equal(JSON.stringify(body).includes("private SQL"), false); } });
