"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { AlertTriangle, ChevronRight, History, RefreshCw, Search, ShieldCheck, UserCog, Users } from "lucide-react";
import type { AdminUserDto, AdminUserRole, AdminUserStatus, AuditEventDto } from "@/app/api/server/user-administration/user-administration.contracts";
import { adminUserQuery } from "./user-list-state";

type Page={items:AdminUserDto[];nextCursor:string|null};
type ErrorBody={error?:{code?:string;message?:string;recovery?:string}};
const roles:AdminUserRole[]=["USER","ADMIN","DEVELOPER","MODERATOR"];
const statuses:AdminUserStatus[]=["ACTIVE","PENDING","INACTIVE","BLOCKED"];
const labels:Record<AdminUserRole|AdminUserStatus,string>={USER:"Usuário",ADMIN:"Administrador",DEVELOPER:"Desenvolvedor",MODERATOR:"Moderador",ACTIVE:"Ativa",PENDING:"Pendente",INACTIVE:"Inativa",BLOCKED:"Bloqueada"};
const tones:Record<AdminUserStatus,string>={ACTIVE:"bg-emerald-50 text-emerald-800 ring-emerald-200",PENDING:"bg-amber-50 text-amber-800 ring-amber-200",INACTIVE:"bg-slate-100 text-slate-700 ring-slate-200",BLOCKED:"bg-rose-50 text-rose-800 ring-rose-200"};

export function UserAdministrationPage(){
 const [page,setPage]=useState<Page|null>(null),[selected,setSelected]=useState<AdminUserDto|null>(null),[audit,setAudit]=useState<AuditEventDto[]>([]),[auditNext,setAuditNext]=useState<string|null>(null),[auditState,setAuditState]=useState<"idle"|"loading"|"error">("idle");
 const [search,setSearch]=useState(""),[role,setRole]=useState(""),[status,setStatus]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(true);
 const [dialog,setDialog]=useState<{kind:"role"|"status";value:string}|null>(null);const [reason,setReason]=useState(""),[busy,setBusy]=useState(false);const [conflict,setConflict]=useState<ErrorBody["error"]>();
 const dialogRef=useRef<HTMLDivElement>(null),triggerRef=useRef<HTMLElement|null>(null),resultRef=useRef<HTMLDivElement>(null),conflictRef=useRef<HTMLDivElement>(null);
 const load=useCallback(async(cursor?:string)=>{setLoading(true);setMessage("");try{const params=adminUserQuery({search,role,status,cursor});const response=await fetch(`/api/admin/users?${params}`,{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error?.message??"Não foi possível carregar os usuários.");setPage(body);}catch(error){setPage(null);setMessage(error instanceof Error?error.message:"Não foi possível carregar os usuários.");}finally{setLoading(false);}},[role,search,status]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),250);return()=>clearTimeout(timer);},[load]);
 async function loadAudit(userId:string,cursor?:string){setAuditState("loading");try{const query=cursor?`?cursor=${encodeURIComponent(cursor)}`:"";const response=await fetch(`/api/admin/users/${userId}/audit${query}`,{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error();setAudit(current=>cursor?[...current,...body.items]:body.items);setAuditNext(body.nextCursor);setAuditState("idle");}catch{if(!cursor)setAudit([]);setAuditState("error");}}
 function choose(user:AdminUserDto){setSelected(user);void loadAudit(user.id);}
 function open(kind:"role"|"status",value:string,event:React.MouseEvent<HTMLButtonElement>){triggerRef.current=event.currentTarget;setReason("");setConflict(undefined);setDialog({kind,value});setTimeout(()=>dialogRef.current?.querySelector<HTMLElement>("textarea")?.focus(),0);}
 function close(){if(busy)return;setDialog(null);setConflict(undefined);setTimeout(()=>triggerRef.current?.focus(),0);}
 async function submit(){if(!selected||!dialog||!reason.trim())return;setBusy(true);setConflict(undefined);try{const kind=dialog.kind;const body=kind==="status"?{expectedStatus:selected.status,expectedRevision:selected.revision,status:dialog.value,reason}:{expectedRole:selected.role,expectedRevision:selected.revision,role:dialog.value,reason};const response=await fetch(`/api/admin/users/${selected.id}/${kind}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(!response.ok){setConflict(result.error);setTimeout(()=>conflictRef.current?.focus(),0);return;}setSelected(result);setDialog(null);await load();await loadAudit(result.id);setMessage(`${kind==="status"?"Estado":"Papel"} de ${result.firstName} atualizado com segurança.`);setTimeout(()=>resultRef.current?.focus(),0);}catch{setConflict({code:"INTERNAL_ERROR",message:"Não foi possível conectar. Tente novamente."});setTimeout(()=>conflictRef.current?.focus(),0);}finally{setBusy(false);}}
 function onDialogKey(event:React.KeyboardEvent){if(event.key==="Escape"&&!busy){event.preventDefault();close();}if(event.key==="Tab"&&dialogRef.current){const nodes=[...dialogRef.current.querySelectorAll<HTMLElement>('button:not([disabled]),textarea:not([disabled])')];if(!nodes.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}}
 return <main className="mx-auto max-w-7xl space-y-6 pb-12">
  <header className="overflow-hidden rounded-3xl bg-gradient-to-br from-emerald-900 via-green-800 to-emerald-700 p-6 text-white shadow-lg md:p-8"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><div className="mb-3 flex items-center gap-2 text-sm font-medium text-emerald-100"><ShieldCheck size={18}/> Administração global</div><h1 className="text-3xl font-bold tracking-tight md:text-4xl">Contas e acessos</h1><p className="mt-2 max-w-2xl text-emerald-50">Consulte usuários e altere estados ou papéis com confirmação, concorrência segura e histórico auditável.</p></div><div className="flex items-center gap-3 rounded-2xl bg-white/10 px-4 py-3 backdrop-blur"><Users/><span className="text-sm"><strong className="block text-xl">{page?.items.length??0}</strong> nesta página</span></div></div></header>
  <section aria-label="Filtros de usuários" className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-[1fr_220px_220px_auto]"><label className="relative"><span className="sr-only">Pesquisar por nome ou email</span><Search className="absolute left-3 top-3 text-slate-400" size={20}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Pesquisar nome ou email" className="w-full rounded-xl border border-slate-300 py-2.5 pl-10 pr-3 focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-200"/></label><Filter label="Papel" value={role} options={roles} onChange={setRole}/><Filter label="Estado" value={status} options={statuses} onChange={setStatus}/><button onClick={()=>void load()} className="flex items-center justify-center gap-2 rounded-xl border border-slate-300 px-4 py-2.5 font-medium text-slate-700 hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-emerald-600"><RefreshCw size={18}/>Atualizar</button></section>
  <div ref={resultRef} tabIndex={-1} role="status" aria-live="polite" className="outline-none">{message&&<p className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-emerald-900">{message}</p>}</div>
  <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_380px]"><section aria-label="Lista de usuários" className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{loading?<State text="Carregando usuários…"/>:!page?<State text="Lista indisponível. Ajuste os filtros ou tente novamente."/>:page.items.length===0?<State text="Nenhum usuário corresponde aos filtros."/>:<ul className="divide-y divide-slate-100">{page.items.map(user=><li key={user.id}><button onClick={()=>choose(user)} className={`group flex w-full items-center gap-4 p-4 text-left hover:bg-emerald-50 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-emerald-600 ${selected?.id===user.id?"bg-emerald-50":""}`}><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-emerald-100 font-bold text-emerald-800">{user.firstName[0]}{user.lastName[0]}</span><span className="min-w-0 flex-1"><strong className="block truncate text-slate-900">{user.firstName} {user.lastName}</strong><span className="block truncate text-sm text-slate-500">{user.email}</span></span><span className="hidden text-sm font-medium text-slate-600 sm:block">{labels[user.role]}</span><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ring-1 ${tones[user.status]}`}>{labels[user.status]}</span><ChevronRight className="text-slate-400 group-hover:text-emerald-700" size={20}/></button></li>)}</ul>}{page?.nextCursor&&<div className="border-t p-3"><button onClick={()=>void load(page.nextCursor!)} className="w-full rounded-xl px-4 py-2 font-medium text-emerald-800 hover:bg-emerald-50">Carregar próxima página</button></div>}</section>
  <aside className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:sticky lg:top-4 lg:self-start">{!selected?<State icon={<UserCog size={28}/>} text="Selecione uma conta para ver detalhes e ações seguras."/>:<><div className="mb-5 border-b border-slate-100 pb-5"><p className="text-xs font-semibold uppercase tracking-wider text-emerald-700">Conta selecionada</p><h2 className="mt-1 text-2xl font-bold text-slate-900">{selected.firstName} {selected.lastName}</h2><p className="break-all text-sm text-slate-500">{selected.email}</p></div><Detail label="Estado" value={labels[selected.status]}/><div className="mt-2 grid grid-cols-2 gap-2">{statuses.filter(item=>item!==selected.status).map(item=><button key={item} onClick={event=>open("status",item,event)} className="rounded-lg border border-slate-300 px-2 py-2 text-sm font-medium hover:border-emerald-600 hover:bg-emerald-50 focus:outline-none focus:ring-2 focus:ring-emerald-600">{labels[item]}</button>)}</div><Detail label="Papel global" value={labels[selected.role]}/><div className="mt-2 grid grid-cols-2 gap-2">{roles.filter(item=>item!==selected.role).map(item=><button key={item} onClick={event=>open("role",item,event)} className="rounded-lg border border-slate-300 px-2 py-2 text-sm font-medium hover:border-emerald-600 hover:bg-emerald-50 focus:outline-none focus:ring-2 focus:ring-emerald-600">{labels[item]}</button>)}</div><div className="mt-6 border-t border-slate-100 pt-5"><h3 className="flex items-center gap-2 font-semibold text-slate-900"><History size={18}/> Histórico recente</h3>{auditState==="loading"&&audit.length===0?<p role="status" className="mt-3 text-sm text-slate-500">Carregando histórico…</p>:auditState==="error"&&audit.length===0?<div role="alert" className="mt-3 text-sm text-rose-800">Não foi possível carregar o histórico. <button className="font-semibold underline" onClick={()=>void loadAudit(selected.id)}>Tentar novamente</button></div>:audit.length===0?<p className="mt-3 text-sm text-slate-500">Nenhuma alteração administrativa registrada.</p>:<><ol className="mt-3 space-y-3">{audit.map(item=><li key={item.id} className="rounded-xl bg-slate-50 p-3 text-sm"><strong>{item.action==="ACCOUNT_STATUS_CHANGED"?"Estado":"Papel"}</strong><p className="text-slate-600">{labels[item.beforeValue]} → {labels[item.afterValue]}</p><p className="mt-1 text-xs text-slate-500">{new Date(item.createdAt).toLocaleString("pt-BR")}</p></li>)}</ol>{auditNext&&<button disabled={auditState==="loading"} onClick={()=>void loadAudit(selected.id,auditNext)} className="mt-3 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold">{auditState==="loading"?"Carregando…":"Carregar mais eventos"}</button>}</>}</div></>}</aside></div>
  {dialog&&selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4" role="presentation"><div ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="admin-dialog-title" aria-describedby="admin-dialog-description" onKeyDown={onDialogKey} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-amber-100 text-amber-800"><AlertTriangle/></span><div><h2 id="admin-dialog-title" className="text-xl font-bold text-slate-900">Confirmar alteração de {dialog.kind==="status"?"estado":"papel"}</h2><p id="admin-dialog-description" className="mt-1 text-sm text-slate-600">{selected.firstName} passará de <strong>{labels[dialog.kind==="status"?selected.status:selected.role]}</strong> para <strong>{labels[dialog.value as keyof typeof labels]}</strong>. Esta ação será auditada.</p></div></div><label className="mt-5 block text-sm font-semibold text-slate-800">Justificativa<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={500} rows={4} className="mt-2 w-full rounded-xl border border-slate-300 p-3 font-normal focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-200" placeholder="Explique por que esta alteração é necessária"/></label>{conflict&&<div ref={conflictRef} role="alert" tabIndex={-1} className="mt-4 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-900"><strong>{conflict.message??"Não foi possível concluir."}</strong>{conflict.recovery==="REFRESH_TARGET"&&<button onClick={()=>{void load();if(selected)void loadAudit(selected.id);}} className="mt-2 block font-semibold underline">Atualizar dados</button>}{conflict.recovery==="ENSURE_ANOTHER_ACTIVE_ADMIN"&&<p className="mt-2">Ative ou promova outro administrador antes de repetir.</p>}</div>}<p role="status" aria-live="polite" className="mt-3 text-sm text-slate-600">{busy?"Processando…":""}</p><div className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button disabled={busy} onClick={close} className="rounded-xl border border-slate-300 px-4 py-2.5 font-semibold text-slate-700 disabled:opacity-50">Cancelar</button><button disabled={busy||!reason.trim()} onClick={()=>void submit()} className="rounded-xl bg-emerald-700 px-4 py-2.5 font-semibold text-white hover:bg-emerald-800 disabled:cursor-not-allowed disabled:opacity-50">Confirmar alteração</button></div></div></div>}
 </main>;
}
function Filter({label,value,options,onChange}:{label:string;value:string;options:readonly string[];onChange:(value:string)=>void}){return <label><span className="sr-only">Filtrar por {label.toLowerCase()}</span><select value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border border-slate-300 px-3 py-2.5 focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-200"><option value="">Todos — {label}</option>{options.map(item=><option key={item} value={item}>{labels[item as keyof typeof labels]}</option>)}</select></label>}
function State({text,icon}:{text:string;icon?:React.ReactNode}){return <div className="flex min-h-48 flex-col items-center justify-center gap-3 p-8 text-center text-slate-500">{icon}{text}</div>}
function Detail({label,value}:{label:string;value:string}){return <div className="mt-5 flex items-center justify-between gap-4"><span className="text-sm text-slate-500">{label}</span><strong className="text-sm text-slate-900">{value}</strong></div>}
