import assert from "node:assert/strict";
import { it } from "node:test";
import type { Prisma, PrismaClient } from "../../src/generated/prisma";
import { DashboardService } from "../../src/app/api/server/services/dashboard.service";
import { DashboardError } from "../../src/app/api/server/dashboard/dashboard.contracts";
const lab="10000000-0000-4000-8000-000000000101", user="10000000-0000-4000-8000-000000000102";
function setup(active=true,linked=true,status="ACTIVE") {
  const calls:{method:string;args:unknown}[]=[];
  const base=new Date("2026-09-18T12:00:00.000Z");
  const areas=Array.from({length:21},(_,index)=>({id:`10000000-0000-4000-8000-${String(200+index).padStart(12,"0")}`,name:`Área ${index}`,createdAt:new Date(base.getTime()-index*1000)}));
  const collections=Array.from({length:4},(_,index)=>({id:`10000000-0000-4000-8000-${String(400+index).padStart(12,"0")}`,confirmedAt:new Date(base.getTime()-index*1000-500),occurredAt:new Date(base.getTime()-5000),collectionArea:{id:areas[0].id,name:areas[0].name}}));
  const tx={user:{findUnique:async()=>({status})},researchersLinked:{findUnique:async()=>linked?{role:"MEMBER",laboratoryRoom:{id:lab,name:"Lab",isActive:active}}:null},collectionArea:{count:async(args:unknown)=>{calls.push({method:"areaCount",args});return 3;},findMany:async(args:unknown)=>{calls.push({method:"areas",args});return areas;}},collectionData:{count:async(args:unknown)=>{calls.push({method:"collectionCount",args});return 4;},findMany:async(args:unknown)=>{calls.push({method:"collections",args});return collections;}}};
  const db={$transaction:async(run:(tx:Prisma.TransactionClient)=>unknown)=>run(tx as unknown as Prisma.TransactionClient)} as unknown as PrismaClient;
  return {service:new DashboardService(db),calls};
}
it("returns real scoped counts and inactive read-only context",async()=>{const {service,calls}=setup(false);const result=await service.summary(user,lab);assert.deepEqual(result.totals,{areas:3,confirmedCollections:4});assert.equal(result.context.readOnly,true);assert.deepEqual((calls[0].args as {where:unknown}).where,{laboratoryRoomId:lab});assert.deepEqual((calls[1].args as {where:{laboratoryRoomId:string}}).where.laboratoryRoomId,lab);});
it("merges sources deterministically, limits to 20 and emits a cursor",async()=>{const {service,calls}=setup();const result=await service.history(user,lab);assert.equal(result.items.length,20);assert.ok(result.page.nextCursor);assert.equal(new Set(result.items.map((item)=>item.id)).size,20);assert.equal(result.items[0].type,"AREA_CREATED");for(const call of calls.filter((entry)=>["areas","collections"].includes(entry.method)))assert.equal((call.args as {take:number}).take,21);});
it("rechecks current membership before reading any source",async()=>{const {service,calls}=setup(true,false);await assert.rejects(service.summary(user,lab),/NOT_FOUND/);assert.equal(calls.length,0);});
it("rejects an ineligible account before reading dashboard sources",async()=>{const {service,calls}=setup(true,true,"BLOCKED");await assert.rejects(service.history(user,lab),/UNAUTHENTICATED/);assert.equal(calls.length,0);});
it("authorizes before rejecting an invalid cursor and does not query sources",async()=>{const {service,calls}=setup();await assert.rejects(service.history(user,lab,"invalid!"),(error)=>error instanceof DashboardError&&error.code==="INVALID_CURSOR");assert.equal(calls.length,0);});
it("selects and publishes only the dashboard allowlist",async()=>{const {service,calls}=setup();const result=await service.history(user,lab);const areaQuery=calls.find((entry)=>entry.method==="areas")!.args as {select:Record<string,unknown>};const collectionQuery=calls.find((entry)=>entry.method==="collections")!.args as {select:Record<string,unknown>};assert.deepEqual(Object.keys(areaQuery.select).sort(),["createdAt","id","name"]);assert.deepEqual(Object.keys(collectionQuery.select).sort(),["collectionArea","confirmedAt","id","occurredAt"]);for(const item of result.items){const serialized=JSON.stringify(item);for(const forbidden of ["userId","email","latitude","longitude","observations","confirmationKey","payload","measurementContractVersion","ihfr","IHFR","diagnosis","scientificState","contractHash"])assert.equal(serialized.includes(forbidden),false);}});
